#!/bin/env sh
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin" 
exec 3<>"/dev/null";exec 0<&3;exec 1>&3;exec 2>&3

#管道消息接收和发送过程,消息空窗期间可用作延时阻塞
MSGPF="/srv/imginit/EVENT.MSGPIPE.INIT"; MSGLN=(); MSGFD=""
MSG_DELAY() {
    [ -p "$MSGPF" ] || return
    [[ "$1" =~ ^"CLOSE"|"CLEAN"$ ]] && { exec 98<&-; MSGFD=""
    [ "$1" == "CLEAN" ] && rm -rf "$MSGPF"; return; }
    [ -z "$MSGFD" ] && { exec 98<>"$MSGPF" && MSGFD=98; }
    [ -z "$MSGFD" ] && return; [ "$1" == "SEND"  ] && { 
    flock -x -w 5 98; echo "${@:2}" >&98; flock -u 98; return; }
    MSGLN=(); [ "$1" == "INIT" ] && return
    read -t "$1" -u 98 MSGLN[0]; MSGLN=( ${MSGLN[0]} ); }

#根据参数指示执行功能或发送控制指令
case "$1" in
"restart" ) MSG_DELAY SEND "SRVRESTART";;
"stop"    ) MSG_DELAY SEND "SRVSTOP";;
*         ) exit 2;;
esac

MSG_DELAY CLOSE; exit 0
